apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: multi-container
spec:
  volumes:
  - name : myvolume
    emptyDir: {}
  containers:
  - image: nginx
    name: c1
    resources: {}
    ports:
      - containerPort: 80
        name : http
    volumeMounts:
    - name: myvolume
      mountPath: /usr/share/nginx/html  
  initContainers:
  - image: busybox
    name: c2
    command: ["/bin/sh", "-c"]
    args: ["wget -O /work-dir/index.html http://neverssl.com/online"]
    resources: {}
    volumeMounts:
    - name: myvolume
      mountPath: /work-dir  
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}