#
#
#
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ckad-pv-claim
  namespace: ckad
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi