apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secret-nginx
  name: secret-nginx
  namespace: ckad
spec:
  containers:
  - image: nginx
    name: secret-nginx
    envFrom:
    - secretRef:
        name: ckad-secrets
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

