#
#
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: default-app-configs
data:
  # property-like keys; each key maps to a simple value
  appame: pgc-tool
  profile: dev
  # file-like keys
  dev.properties: | # YAML for multi-line string
    env=DEV
    db.url=sybdevol@jpmchase.com
  dev.properties: | # YAML for multi-line string
    env=DEV
    db.url=sybdevol@jpmchase.com
  uat.properties: | # YAML for multi-line string
    env=UAT
    db.url=sybuatol@jpmchase.com
  prod.properties: | # YAML for multi-line string
    env=PROD
    db.url=sybuatol@jpmchase.com