apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webapp
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webapp
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
#
#
#

kubectl scale deployment webapp --replicas=15
kubectl set image deployment webapp nginx=nginx:1.17.1
kubectl rollout status deploy webapp
kubectl rollout history deployment webapp
kubectl rollout undo deployment webapp
kubectl rollout undo deployment webapp --to-revision=3
kubectl rollout history deploy webapp --revision=7
kubectl rollout pause deploy webapp 
