#
#
#
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    livenessProbe:
      exec:
        command:
          - ls
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
#
#
#
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    livenessProbe:
      tcpSocket:                    # add
        port: 80                    # add
      initialDelaySeconds: 10       # add
      periodSeconds: 15             # add
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
#
#
#
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    livenessProbe:
      httpGet:                      # add
        path: /healthz              # add
        port: 8080                  # add
        httpHeaders:                # add    
        - name: Custom-Header       # add
          value: Awesome            # add
        - name: Accept              # add
          value: application/json   # add
      initialDelaySeconds: 10       # add
      periodSeconds: 15             # add
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}