apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sc-volume-test
  name: sc-volume-test
spec:
  volumes:
  - name: secret-volume
    secret: 
      secretName: default-secrets
  containers:
  - image: nginx
    name: nginx
    ports:
    - name: http 
      containerPort: 80
      protocol: TCP
    resources: {}
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: default-secrets
          key: name
    - name: SECRET_PASSWD
      valueFrom:
        secretKeyRef:
          name: default-secrets
          key: passwd
    envFrom:
    - secretRef:
        name: default-secrets     
    volumeMounts:
    - mountPath: /app/secrets
      name: secret-volume           # name must match the volume name below
      readOnly: true
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

# kubectl exec -it sc-volume-test -- cat /app/secrets/name
# kubectl exec -it sc-volume-test -- cat /app/secrets/passwd
#