apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: cm-env
  name: cm-env
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    env:
      - name: USERNAME
        valueFrom:
          configMapKeyRef: 
            name: default-config-map 
            key: name
      - name: UPASSWD 
        valueFrom: 
          configMapKeyRef: 
            name: default-config-map
            key: passwd
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}  
