#
# kubectl create cm cm-configs -n i100121 --from-file=dev.properties=configs/app.dev.properties --from-file=uat.properties=configs/app.dev.properties --from-file=prod.properties=configs/app.dev.properties --from-literal=appame=pgc-tool --from-literal=profile=dev --from-literal=userid=i100121 --from-literal=password=Accoo7@k47 --dry-run=client -o yaml
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-configs
data:
  # property-like keys; each key maps to a simple value
  appame: pgc-tool
  profile: dev
  userid: i100121
  password: Accoo7@k47
  # file-like keys
  dev.properties: | # YAML for multi-line string
    env=DEV
    db.url=sybdevol@jpmchase.com
  uat.properties: | # YAML for multi-line string
    env=UAT
    db.url=sybuatol@jpmchase.com
  prod.properties: | # YAML for multi-line string
    env=PROD
    db.url=sybuatol@jpmchase.com

