apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: cm-envfrom
  name: cm-envfrom
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    envFrom:
    - configMapRef:
       name: multikey-cm
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
