#
# kubectl create job ckad-job -n ckad --image=busybox $do -- /bin/sh -c "date;echo 'This is sample k8s job'"
#
apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: ckad-job
  namespace: ckad
spec:
  completions: 5             # Run 10 times    
  parallelism: 5             # Run in parallelism
  activeDeadlineSeconds: 30  # it will be automatically terminated by kubernetes if it takes more than 30 seconds to execute
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        args: ["date; echo '...... This is sample k8s job .... '"]
        image: busybox
        name: hello-job
        resources: {}
      restartPolicy: Never
status: {}
