apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-runas
  name: pod-runas
spec:
  securityContext:
    runAsUser: root
    runAsGroup: root
    capabilities: # and this
      add: ["NET_ADMIN", "SYS_TIME"] # this as well
  containers:
  - image: nginx
    name: nginx
    resources:
      limits:
        memory: 64Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
