apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
  labels:
    app: task-pv-pod
spec:
  volumes:
  - name: test-volume
    hostPath:
      path: /var/lib/docker
      type: DirectoryOrCreate
  - name: c-drive
    hostPath:
      path: /run/desktop/mnt/host/c
      type: DirectoryOrCreate
  - name: d-drive
    hostPath:
      path: /run/desktop/mnt/host/d
      type: DirectoryOrCreate
  - name: task-pv-storage
    persistentVolumeClaim:
      claimName: task-pv-claim
  containers:
  - image: nginx
    name: nginx
    ports:
      - containerPort: 80
        name: "http-server"
    volumeMounts:
    - mountPath: "/ckad"
      name: test-volume
    - mountPath: "/drives/c"
      name: c-drive
    - mountPath: "/drives/d"
      name: d-drive  
    - mountPath: "/usr/share/nginx/html"
      name: task-pv-storage  
  