apiVersion: v1
kind: Pod
metadata:
  name: hostpath-volume-test
spec:
  volumes:
  - name: hostpath-volume
    hostPath:
      path: /var/lib/docker/ckad        # directory location on host
      type: Directory                   # this field is optional
  containers:
  - image: nginx
    name: nginx
    ports:
      - containerPort: 80
        name: "http-server"
    volumeMounts:
    - mountPath: "/hostpath"
      name: hostpath-volume