apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: liveness-exec
  name: liveness-exec
  namespace: ckad
spec:
  containers:
  - name: busybox
    image: busybox
    args:
      - /bin/sh
      - -c
      - touch /tmp/healthy; sleep 60; rm -rf /tmp/healthy; sleep 300;
    livenessProbe:
      initialDelaySeconds: 15
      periodSeconds: 5
      exec:
        command:
        - cat
        - /tmp/healthy
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
