apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: liveness-http
  name: liveness-http
  namespace: ckad
spec:
  containers:
  - name: liveness
    image: k8s.gcr.io/liveness
    args:
    - /server
    ports:
    - containerPort: 8080
      name: liveness-port
      hostPort: 8080  
    livenessProbe:
      initialDelaySeconds: 3
      periodSeconds: 3
      httpGet:
        path: /healthz
        port: 8080
        httpHeaders:
        - name: Custom-Header
          value: Awesome
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
