apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-runas
  name: pod-runas
spec:
  # Below lines need to add 
  securityContext:
    runAsUser: 0
    runAsGroup: 10
    fsGroup: 10
  #  
  containers:
  - image: nginx
    name: nginx
    resources:
      limits:
        memory: 64Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

#
# id -u username
# id -g username
# id -G username
# id username
# id
# root@secure-pod:/tmp# id
# uid=0(root) gid=10(uucp) groups=10(uucp)