apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-runas
  name: pod-runas
spec:
  # Below lines need to add 
  securityContext:
    runAsUser: root
    runAsGroup: root
    fsGroup: root
  #  
  containers:
  - image: nginx
    name: nginx
    resources:
      limits:
        memory: 64Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
