apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-runas
  name: pod-runas
spec:
  securityContext:
    runAsUser: root
    runAsGroup: root
  containers:
  - image: nginx
    name: nginx
    securityContext:
      capabilities: # and this
        add: ["NET_ADMIN", "SYS_TIME"] # this as well
    resources:
      limits:
        memory: 64Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
