#
# kubectl create sa i100121 $do
#
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: i100121
---

# Use Service Account in pod
# kubectl run nginx-pod --image=nginx --port=80 --serviceaccount=i100121 $do
#
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-pod
  name: nginx-pod
spec:
  containers:
  - image: nginx
    name: nginx-pod
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  serviceAccountName: i100121
status: {}

