#
# kubectl autoscale deploy webapp --min=10 --max=20 --cpu-percent=85
#

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: null
  name: webapp
spec:
  maxReplicas: 20
  minReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webapp
  targetCPUUtilizationPercentage: 85
status:
  currentReplicas: 0
  desiredReplicas: 0
  
