apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi-con-pod
  name: multi-con-pod
spec:
  volumes:
    - name: logs-vol
      emptyDir: {}
  containers:
  - image: busybox 
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo ‘Hi I am from Main container’ >> /var/log/index.html; sleep5; done"]    
    name: main-car
    resources: {}
    volumeMounts:
      - name: logs-vol
        mountPath: "/var/log"
  - image: nginx
    name: side-car
    ports:
      - name: http-port
        containerPort: 80
        protocol: TCP
    resources: {}
    volumeMounts:
      - name: logs-vol
        mountPath: "/usr/share/nginx/html"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
